name: Janitor

on:
  schedule:
    - cron: '0 0 * * *' # Daily at midnight UTC
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Dry run"
        type: boolean
        default: true

permissions:
  actions: write
  contents: read

jobs:
  cleanup:
    uses: canonical/launchpad-actions/.github/workflows/janitor.yaml@d37e57af16120fba0055931e77518a5f9edf7513
    with:
      dry_run: ${{ inputs.dry_run == true }}
      keep_workflows: "pipeline.yaml,prek.yaml"
